name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: xcodebuild -project WebViewScreenSaver.xcodeproj -scheme WebViewScreenSaver -configuration Release clean archive -archivePath buildArchive/build.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

